name: AWS Access

on:
  push:
    branches:
      - corgi

permissions:
  id-token: write
  contents: read

  
jobs:
  aws:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::009661764077:role/lambdaRole
          aws-region: us-east-1

      - name: Invoke Lambda
        run: |
          aws lambda invoke \
            --function-name nslookupv2 \
            --region us-east-1 \
            --payload '{"domain": "example.com"}' \
            --cli-binary-format raw-in-base64-out \
            output.json

      - name: Display Lambda Response
        run: cat output.json