name: AWS Access

on:
  push:
    branches:
      - corgi

permissions:
  id-token: write
  contents: read

jobs:
  aws:
    runs-on: ubuntu-latest

    steps:
      - name: AWS commands
        run: |
          aws sts get-caller-identity
          aws s3 ls
          aws lambda list-functions --region us-east-1